apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
spec:
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
    - mountPath: /mounted-data
      name: data-volume
  volumes:
  - name: data-volume
    emptyDir: {}