apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client # cible la ressource (pod) ayant le label app:client
  ports:
    - port: 3300
      targetPort: 3000 # cible l'application serveur conteneurisée dans le Pod
      nodePort: 30007
  